services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kb-backend
    environment:
      - AWS_REGION=${AWS_REGION:-us-west-2}
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-west-2}
      - AWS_PROFILE=default
      - KNOWLEDGE_BASE_ID=${KNOWLEDGE_BASE_ID:-DFVMT0Y6LF}
      - MODEL_ARN=${MODEL_ARN:-arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0}
      - PORT=8000
      - HOST=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      # Mount AWS credentials if using local AWS config
      - ~/.aws:/home/app/.aws:ro
    networks:
      - kb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kb-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - kb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kb-network:
    driver: bridge

volumes:
  aws-credentials:
    driver: local 